INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(POCO_INCLUDE_DIR Poco/Poco.h
    PATHS $ENV{POCODIR}
    PATH_SUFFIXES include
    )
FIND_LIBRARY(POCO_LIBRARY_OPTIMIZED
    NAMES PocoFoundation
    PATHS $ENV{POCODIR}
    PATH_SUFFIXES lib
    )
FIND_LIBRARY(POCO_LIBRARY_DEBUG
    NAMES PocoFoundationd PocoFoundation_d PocoFoundationD PocoFoundation_D
    PATHS $ENV{POCODIR}
    PATH_SUFFIXES lib
    )

# Handle the REQUIRED argument and set POCO_FOUND
FIND_PACKAGE_HANDLE_STANDARD_ARGS(POCO DEFAULT_MSG
    POCO_LIBRARY_OPTIMIZED
    POCO_INCLUDE_DIR
    )

MARK_AS_ADVANCED(
    POCO_INCLUDE_DIR
    POCO_LIBRARY_OPTIMIZED
    POCO_LIBRARY_DEBUG
    )
