cc_binary(
    name = "load_scans",
    srcs = [
        "load_scans.cpp",
    ],
    deps = [
        "//core:L3",
        "@boost//:filesystem",
        "@boost//:thread",
        "@poco",
        "@gsl",
        "@config",
        "@com_github_google_glog//:glog",
    ]
)
cc_binary(
    name = "experience_builder",
    srcs = [
        "experience_builder.cpp",
    ],
    deps = [
        "//core:L3",
        "@boost//:filesystem",
        "@boost//:thread",
        "@poco",
        "@gsl",
        "@config",
        "@com_github_google_glog//:glog",
    ]
)

cc_binary(
    name = "reflectance_builder",
    srcs = [
        "reflectance_builder.cpp",
    ],
    deps = [
        "//core:L3",
        "@boost//:filesystem",
        "@boost//:thread",
        "@poco",
        "@gsl",
        "@config",
        "@com_github_google_glog//:glog",
    ]
)

cc_binary(
    name = "LHLV_filter",
    srcs = [
        "LHLV_filter.cpp",
    ],
    deps = [
        "//core:L3",
        "@boost//:filesystem",
        "@boost//:thread",
        "@poco",
        "@gsl",
        "@config",
    ]
)
