cc_library(
    name = "interface",
    srcs = [
        "Interface.cpp",
    ],
    hdrs = [
        "Interface.h",
    ],
    includes = [
        ".",
    ],
    deps = [
      "@lua",
      "@boost//:regex",
    ],
    visibility = ["//visibility:public"],
)
